### ISSUE TITLE
non-integer bit diameters cause a crash

### ISSUE THREAD

**Issue by nathanielstenzel** [nathanielstenzel/bucket_mill#2]
A non-integer bit diameters cause a crash. See below.
> DONE WITH RENDER
> Traceback (most recent call last):
>   File "bucket_mill.py", line 988, in <module>
>     bottom = where(filter_grid(bottom,min_value=(min_stl_z*stl_detail),input_filter='nearby',size=(2+2*bit_diameter)*stl_detail), bottom, do_not_cut)
>   File "bucket_mill.py", line 729, in filter_grid
>     mask = ones((size,size))
>   File "/usr/lib64/python2.7/site-packages/numpy/core/numeric.py", line 192, in ones
>     a = empty(shape, dtype, order)
> TypeError: 'float' object cannot be interpreted as an index
>

**Comment by nathanielstenzel** [comment]
This is at least partially fixed now, but I am not sure if it is fixed in a proper way. There were a few spots of code where I tell it to just use the integer version of the bit diameter. This needs more testing.

**Comment by nathanielstenzel** [comment]
A final cut test showed movement at the max Y border when using a non-integer bit diameter. That movement looks like it is above Z=0. This should not be a problem unless the clamp is there.
